PS02_CoffeStreet-master/CoffeStreet/Controllers/CatalogController.cs
using CoffeStreet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoffeStreet.Controllers
{
    public class CatalogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public CatalogController()
        {
            //lista de categorias de productos
            var ptypes = db.ProductTypes.ToList();
            ViewData.Add("categories", ptypes);
        }

        // GET: Catalog
        public ActionResult Index()
        {
            return View();
        }

        // GET: Catalog/Details/Te
        public ActionResult Details(string category)
        {
            
            var list = db.Products.Where(p => p.Type == category && p.Quantity > 0).ToList();
            return View(list);
        }

        // GET: Catalog/Product/1
        public ActionResult Product(int pId)
        {
            var product = db.Products.Find(pId);
            return View(product);
        }

        // POST: Crear orden
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetOrder([Bind(Include = "ProductId,ClientName,Quantity")] Order order)
        {
            if (ModelState.IsValid)
            {
                order.Date = DateTime.Now;
                db.Orders.Add(order);
                Product p = db.Products.Find(order.ProductId);
                p.Quantity -= order.Quantity;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ProductId = new SelectList(db.Products, "Id", "ProductName");
            return View();
        }
    }
}

PS02_CoffeStreet-master/CoffeStreet/Controllers/HomeController.cs
using CoffeStreet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoffeStreet.Controllers
{
    //[Authorize]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public HomeController()
        {
            var u = User;
            if (u == null || !u.Identity.IsAuthenticated)
            {
                //lista de categorias de productos
                var ptypes = db.ProductTypes.ToList();
                var top5 = db.Products.OrderByDescending(pr => db.Orders.Count(o => o.ProductId == pr.Id)).Take(5).ToList();
                ViewData.Add("categories", ptypes);
                top5.ForEach(pr =>
                {
                    if (!String.IsNullOrEmpty(pr.ImagePath))
                    {
                        string[] im = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(pr.ImagePath)).Split(',');
                        byte[] imB = new byte[im.Length];
                        for (int j = 0; j < im.Length; j++)
                        {
                            imB[j] = byte.Parse(im[j]);
                        }
                        pr.ImagePath = Convert.ToBase64String(imB);
                    }
                });
                ViewData.Add("top5", top5);
            }
        }
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Orders");
            }

            
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PS02_CoffeStreet-master/CoffeStreet/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PS02_CoffeStreet-master/CoffeStreet/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PS02_CoffeStreet-master/CoffeStreet/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!-- featured post -->
<section>
    <div class="container-fluid p-sm-0">
        <div class="row featured-post-slider">
            @foreach (CoffeStreet.Models.Product pr in (ViewData["top5"] as List<CoffeStreet.Models.Product>))
            {
                <div class="col-lg-3 col-sm-6 mb-2 mb-lg-0 px-1">
                    <article class="card bg-dark text-center text-white border-0 rounded-0">
                        <img class="card-img rounded-0 img-fluid w-100" src="data:image/jpg;base64, @pr.ImagePath" alt="post-thumb">
                        <div class="card-img-overlay">
                            <div class="card-content">
                                <p class="text-uppercase">Por solo $@pr.Cost</p>
                                <h4 class="card-title mb-4"><a class="text-white" href="blog-single.html">@pr.ProductName</a></h4>
                                <a class="btn btn-outline-light" href="@Url.Action("Product", "Catalog", new { pId = pr.Id })">Ordenar</a>
                            </div>
                        </div>
                    </article>
                </div>
            }

        </div>
    </div>
</section>
<!-- /featured post -->

<div class="container">
    <div class="section pb-0">
        <div class="col-12 mb-100">
            <article data-file="articles/b.html" data-target="article" class="article-full-width article-right">
                <div class="post-image">
                    <img class="img-fluid" src="~/Content/img/coffee-3809443_640.jpg" alt="post-thumb">
                </div>
                <div class="post-content">
                    <ul class="list-inline d-flex justify-content-between border-bottom post-meta pb-2 mb-4">
                        <li class="list-inline-item"><i class="ti-calendar mr-2"></i>2 Febrero, 2020</li>
                    </ul>
                    <h4 class="mb-4">
                        <a href="blog-single.html" class="text-dark">
                            Nuestro café de grano
                        </a>
                    </h4>
                    <p class="mb-0 post-summary">
                        Hola, somos Perso Coffe, nuestro café en grano tiene notas de nougat, almendra, con toque de miel. Lo puedes pedir por Rappi o hablar directamente al café.  Podemos moler el café para ti.
                    </p>
                    <a class="btn btn-transparent mb-4" href="blog-single.html">Ordenar</a>
                </div>
            </article>
        </div>
    </div>
</div>

<!-- instagram -->
<section>
    <div class="container-fluid px-0">
        <div class="row no-gutters instagram-slider" id="instafeed" data-userId="4044026246"
             data-accessToken="4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"></div>
    </div>
</section>
<!-- /instagram -->